### ISSUE TITLE
Add missing sigma calculation for pfind output

### ISSUE THREAD

**Issue by pyuxiang** [franciumxzf/pfind#8]
Once the final time and frequency offset is calculated, we should do one more cross correlation with the modified timestamps and output the significance of the peak (sigma), in line with the output of pfind.c.

This is distinct from the double pfind run on (alice, bob) and (bob, alice) - this belongs to the tests to check for algorithm correctness.

**Comment by franciumxzf** [comment]
In the previous pfind, we use the sigma to decide whether the peak is strong enough to start tracking. In this current pfind, as we run `time_freq` multiple times to make sure the frequency result is correct, so we will put aside this sigma calculation aside first.
